### ISSUE TITLE
2022大厂面经中长亭面试第十五题求答案

### ISSUE THREAD

**Issue by zxcvtest** [biggerduck/RedTeamNotes#1]
如题，shiro 反序列化漏洞如果cookie 中的payload 过长被waf 拦截如何绕waf？

**Comment by biggerduck** [comment]
几个思路：
1、xz上有究极反序列化payload缩小技术，可以看看。
2、实现一个loader在cookie中，把payload放到body里面。
3、单纯过waf，改正常的http方法为xxx（任意未知方法），waf不解析，后端解析数据不依赖http方法，能过。

**Comment by zxcvtest** [comment]
> 几个思路： 1、xz上有究极反序列化payload缩小技术，可以看看。 2、实现一个loader在cookie中，把payload放到body里面。 3、单纯过waf，改正常的http方法为xxx（任意未知方法），waf不解析，后端解析数据不依赖http方法，能过。
收到，谢谢师傅指点
